### ISSUE TITLE
Feature Request: device triggers from outside Konnected

### ISSUE THREAD

**Issue by jibberjabberish** [mkormendy/homebridge-konnected#36]
I have Google/Nest Protect Smoke Detectors that are brought into Homekit via the Starling Hub... I would really like to trigger the Noonlight alarm from them... which would be great to do in coordination with your app.

I'm sure I could set up a Shortcut separately to call a Noonlight API endpoint directly from the Smoke Detectors... but not ideal.

**Comment by mkormendy** [comment]
This would be completed in two components already in requested features:
1. noonlight integration #21
2. virtual zones #22
