### ISSUE TITLE
Feature Request: option to expose individual contacts, glass breaks and sirens to Homekit

### ISSUE THREAD

**Issue by jibberjabberish** [mkormendy/homebridge-konnected#37]
Maybe I am experiencing a bug, but it seems like the only thing exposed to Homekit is the alarm Off/Away button. But I thought I would have access to contact sensors so I can do automations like "garage entrance open, turn on Garage lights"... but I don't see any individual contact sensors being exposed to Homekit. And I apparently can't run a Homekit integration at the same time as the Hubitat integration (to expose individual sensors to Homekit), because they overwrite the Konnected Pro board's configuration.

I understand not everyone would want ALL sensors exposed to Homekit, so this would ideally be a slider button on each zone configuration.

**Comment by mkormendy** [comment]
Apologies for the late reply. The plugin does in fact expose sensors to HomeKit. You may need to follow the configuration instructions a little more closely. As well, HomeKit doesn't expose a full tiles in the Home app for sensors; the sensors are usually found in the rooms themselves in the upper region of the user interface of the app when they open and close.
