### ISSUE TITLE
Unable to Add Accessory: "Accessory is out of compliance."

### ISSUE THREAD

**Issue by pickanothername** [mkormendy/homebridge-konnected#39]
**Bug Description**
After switching Konnected to a child bridge, I am no longer able to pair it with HomeKit. Unclear if switching to child bridge or just unpairing caused this issue.

**Steps To Reproduce**
1. Pair Konnected normally
2. Switch Konnected to child bridge mode in Homebridge settings
3. Attempt to pair to Homekit using the child bridge's QR code
4. _Error: "Unable to Add Accessory. Accessory is out of compliance."_

**Expected Behavior**
Konnected pairs to HomeKit as a child bridge (hub)

**Environment**
* Homebridge System: 
  * Node.js Version: v18.17.1
  * NPM Version: v9.6.7
  * Homebridge/HOOBS Version: Homebridge v1.6.1
  * Operating System: Alpine Linux
  * Process Supervisor: Docker
* Konnected Panel(s):
  * Panel Hardware Version: v1
  * Firmware Version: 3.0.0
  * Addon Panel(s): 6-Zone Alarm Panel (1)
  * Interface Panel(s): 6-Zone /w Siren Output (1)

**Attach Files to Support Your Experience**
![43FA9921-F065-4229-AE4B-134739E5F224_1_201_a](https://github.com/mkormendy/homebridge-konnected/assets/1732093/43ab6900-f408-438e-94a4-18e6e3d69a6d)

**Additional Relevant Information**
I'm on iOS/AudioOS 17.0.

**Comment by mkormendy** [comment]
Please don't use this in bridge mode. It is untested.

**Comment by mkormendy** [comment]
You will have to delete all of your accessory data for the Konnected plugin to re-enable it in accessory mode.

**Comment by pickanothername** [comment]
I see. I guess I'll change this to a feature request then, because bridge support would be invaluable for this plugin.

**Comment by mkormendy** [comment]
Please list the perceived benefits in that ticket.

**Comment by pickanothername** [comment]
> Please list the perceived benefits in that ticket.

I'd like to amend my statement- while I would still like child bridge support, ultimately the issue I'm trying to resolve is issue #2.
Every time Homebridge restarts or loses connection, the security system is triggered.
