### ISSUE TITLE
Feature Request: support for Konnected Garage Door Opener in homebridge-konnected

### ISSUE THREAD

**Issue by tbsaunders1** [mkormendy/homebridge-konnected#45]
I can't find out if the Konnected Garage Door Opener is supported by this plugin. If not currently supported, can this be added? I do not have one of the devices yet but am looking at this as a replacement for my garage door automation post-MyQ.

I have two Konnected panels for my hardwired alarm system feeding into my homebridge setup.

**Comment by mkormendy** [comment]
At this time there is no planned garage door opener support.

**Comment by tbsaunders1** [comment]
Ok, thanks for letting me know.
