### ISSUE TITLE
Only one button

### ISSUE THREAD

**Issue by plasticfist** [mkormendy/homebridge-konnected#55]
**Describe the bug**
Just getting started with home bridge, hoping I missed something, have tried all advice still no joy.  Have two Konnected Pro, and two addon boards, it finds them just fine, but configured switches and temp/hum do not show up.   This is all that shows up...
![button](https://github.com/user-attachments/assets/bd9fd643-f995-411b-9ed9-e6d82c8fb55b)

**To Reproduce**
Replace this text with steps to reproduce the bug or issue you're having:
1. load plugin
2. configure switches and temp/hum
3. they do not appear in homebridge

**Expected Behavior**
* two switches that can be turned on/off, temp/hum visible somewhere?

Notes: 
- Do not use Konnected as a traditional alarm system
- currently integrated with homeassistant, to show/monitor window/door open/close status, and temp/hum in two locations.  Was hoping this integration would enable asking Siri if all windows and doors are closed, and perhaps for temp/hum information, but these may be feature requests.
- The Konnected output switches control a relay that opens/closes garage doors, and on the same board setup separate contact closure reporting on open/close status.   Was hoping to ask Siri to open/close each garage door.

**Environment (please complete the following information as best possible)**
* Homebridge System:

OS | Debian GNU/Linux Bookworm (12)
-- | --
10.0.1.88
fe80::be24:11ff:fecd:23b3
lxc-debian12-homebridge
homebridge
v20.18.0
/opt/homebridge/bin
/var/lib/homebridge
/var/lib/homebridge/config.json
/var/lib/homebridge/node_modules
* Konnected Panel(s):
  * 2 x KonnectedPro 1.3.7, Firmware 1.1.2-795643
  * WifiAddOn Software 3.1.5 Firmware 3.0.0
  * WifiAddOn Software 3.1.4 Firmware 3.0.0

**Additional Relevant Information**

{
            "name": "Konnected",
            "advanced": {
                "exitDelaySettings": {
                    "audibleBeeperModes": [
                        "false",
                        "false",
                        "1"
                    ]
                }
            },
            "panels": [
                {
                    "name": "20996f",
                    "ipAddress": "10.0.1.5",
                    "port": 9123,
                    "blink": false
                },
                {
                    "name": "Konnected Pro1",
                    "uuid": "8f655392-a778-4fee-97b9-eb3c61050010",
                    "ipAddress": "10.0.1.7",
                    "port": 9123,
                    "blink": false
                },
                {
                    "name": "Konnected Pro2",
                    "uuid": "8f655392-a778-4fee-97b9-8440f520996f",
                    "ipAddress": "10.0.1.5",
                    "port": 9123,
                    "blink": false
                },
                {
                    "name": "Konnected V1-V2",
                    "uuid": "8f655392-a778-4fee-97b9-48259186f5cea",
                    "ipAddress": "10.0.1.10",
                    "port": 15298,
                    "blink": false
                },
                {
                    "name": "Konnected V1-V2-b",
                    "uuid": "8f655392-a778-4fee-97b9-48259186f6b85",
                    "ipAddress": "10.0.1.26",
                    "port": 15302,
                    "blink": false,
                    "zones": [
                        {
                            "enabled": true,
                            "zoneNumber": "7",
                            "zoneType": "switch",
                            "zoneLocation": "Other",
                            "switchSettings": {
                                "triggerableModes": [
                                    "0",
                                    "2",
                                    "1"
                                ]
                            }
                        },
                        {
                            "enabled": true,
                            "zoneNumber": "9",
                            "zoneType": "switch",
                            "zoneLocation": "Other"
                        },
                        {
                            "enabled": true,
                            "zoneNumber": "1",
                            "zoneType": "humidtemp",
                            "zoneLocation": "Other"
                        }
                    ]
                },
                {
                    "name": "Konnected V1-V2-c",
                    "uuid": "8f655392-a778-4fee-97b9-48259186f6b60",
                    "ipAddress": "10.0.1.25",
                    "port": 15301,
                    "blink": false
                }
            ],
            "platform": "konnected"
        },

**Comment by mkormendy** [comment]
@plasticfist unfortunately Konnected devices themselves don't support simultaneous provisioning by multiple Home Automation software, that's likely why it isn't working.

It's either Homebridge or Home Assistant, but not both.

There is a way to expose Home Assistant devices/sensors/switches etc to HomeKit directly without Homebridge .. but I believe it's slower in response time, however I have never tried using that before.

**Comment by mkormendy** [comment]
@plasticfist also, asking Siri if doors are open or what the temperature is based on sensors is handled by iOS and the HomeKit integration with Siri and nothing in Homebridge or this plugin has control over that.
